[package]
name = "pulse-ring"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
smithay-client-toolkit = { version = "0.21", features = ["system"] }
wayland-client = { version = "0.31", features = ["system"] }
cpal = "0.15"
realfft = "3.5"
rustfft = "6.4"
crossbeam-channel = "0.5"
anyhow = "1"
log = "0.4"
env_logger = "0.11"
wgpu = "30"
pollster = "1"
raw-window-handle = "0.6"
bytemuck = { version = "1", features = ["derive"] }
wayland-protocols = { version = "0.32.13", features = ["staging"] }
png = "0.18"
libc = "0.2.189"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
mlua = { version = "0.10", default-features = false, features = ["lua54", "vendored"] }
ab_glyph = "0.2.32"
rusttype = "0.9"
libloading = "0.9.0"
serde_json = "1"
fontdue = "0.9"

[dev-dependencies]
naga = "30.0.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
